/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ReentrantNFTMarketLenderStartLoan,
  ReentrantNFTMarketLenderStartLoanInterface,
} from "../ReentrantNFTMarketLenderStartLoan";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract INFTMarket",
        name: "_contract",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "Contract",
    outputs: [
      {
        internalType: "contract INFTMarket",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "collection",
        type: "address",
      },
      {
        internalType: "address",
        name: "loanToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint128",
        name: "principal",
        type: "uint128",
      },
      {
        internalType: "uint64",
        name: "interestRate",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "maturity",
        type: "uint64",
      },
    ],
    name: "proposeLoan",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161037738038061037783398101604081905261002f91610054565b600080546001600160a01b0319166001600160a01b0392909216919091179055610084565b60006020828403121561006657600080fd5b81516001600160a01b038116811461007d57600080fd5b9392505050565b6102e4806100936000396000f3fe60806040526004361061002d5760003560e01c80635af77fff1461009e57806376b27621146100da57600080fd5b36610099576000805460405163e58b87dd60e01b81526004810192909252600160248301526001600160a01b03169063e58b87dd90604401600060405180830381600087803b15801561007f57600080fd5b505af1158015610093573d6000803e3d6000fd5b50505050005b600080fd5b3480156100aa57600080fd5b506000546100be906001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f35b3480156100e657600080fd5b506100fa6100f5366004610233565b6100fc565b005b60005460405163095ea7b360e01b81526001600160a01b039182166004820152602481018690529087169063095ea7b390604401600060405180830381600087803b15801561014a57600080fd5b505af115801561015e573d6000803e3d6000fd5b50506000546040516376b2762160e01b81526001600160a01b038a811660048301528981166024830152604482018990526001600160801b038816606483015267ffffffffffffffff8088166084840152861660a483015290911692506376b27621915060c401600060405180830381600087803b1580156101df57600080fd5b505af11580156101f3573d6000803e3d6000fd5b50505050505050505050565b80356001600160a01b038116811461021657600080fd5b919050565b803567ffffffffffffffff8116811461021657600080fd5b60008060008060008060c0878903121561024c57600080fd5b610255876101ff565b9550610263602088016101ff565b94506040870135935060608701356001600160801b038116811461028657600080fd5b92506102946080880161021b565b91506102a260a0880161021b565b9050929550929550929556fea2646970667358221220ea9cf6c12d6b0ffcf3a1252bbaf2960c1115920dfa3bf04b36559ebadb4f120964736f6c634300080a0033";

type ReentrantNFTMarketLenderStartLoanConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ReentrantNFTMarketLenderStartLoanConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ReentrantNFTMarketLenderStartLoan__factory extends ContractFactory {
  constructor(...args: ReentrantNFTMarketLenderStartLoanConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "ReentrantNFTMarketLenderStartLoan";
  }

  deploy(
    _contract: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ReentrantNFTMarketLenderStartLoan> {
    return super.deploy(
      _contract,
      overrides || {}
    ) as Promise<ReentrantNFTMarketLenderStartLoan>;
  }
  getDeployTransaction(
    _contract: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_contract, overrides || {});
  }
  attach(address: string): ReentrantNFTMarketLenderStartLoan {
    return super.attach(address) as ReentrantNFTMarketLenderStartLoan;
  }
  connect(signer: Signer): ReentrantNFTMarketLenderStartLoan__factory {
    return super.connect(signer) as ReentrantNFTMarketLenderStartLoan__factory;
  }
  static readonly contractName: "ReentrantNFTMarketLenderStartLoan";
  public readonly contractName: "ReentrantNFTMarketLenderStartLoan";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ReentrantNFTMarketLenderStartLoanInterface {
    return new utils.Interface(
      _abi
    ) as ReentrantNFTMarketLenderStartLoanInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ReentrantNFTMarketLenderStartLoan {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ReentrantNFTMarketLenderStartLoan;
  }
}
