/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ReentrantNFTMarketWithdrawBNBInterface
  extends utils.Interface {
  contractName: "ReentrantNFTMarketWithdrawBNB";
  functions: {
    "Contract()": FunctionFragment;
    "counterOffer(address,address,uint256,uint128,uint64,uint64)": FunctionFragment;
    "withdrawBNB(address,uint256,address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "Contract", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "counterOffer",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawBNB",
    values: [string, BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "Contract", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "counterOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawBNB",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ReentrantNFTMarketWithdrawBNB extends BaseContract {
  contractName: "ReentrantNFTMarketWithdrawBNB";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ReentrantNFTMarketWithdrawBNBInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    Contract(overrides?: CallOverrides): Promise<[string]>;

    counterOffer(
      collection: string,
      loanToken: string,
      tokenId: BigNumberish,
      principal: BigNumberish,
      interestRate: BigNumberish,
      maturity: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawBNB(
      collection: string,
      tokenId: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  Contract(overrides?: CallOverrides): Promise<string>;

  counterOffer(
    collection: string,
    loanToken: string,
    tokenId: BigNumberish,
    principal: BigNumberish,
    interestRate: BigNumberish,
    maturity: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawBNB(
    collection: string,
    tokenId: BigNumberish,
    to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    Contract(overrides?: CallOverrides): Promise<string>;

    counterOffer(
      collection: string,
      loanToken: string,
      tokenId: BigNumberish,
      principal: BigNumberish,
      interestRate: BigNumberish,
      maturity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawBNB(
      collection: string,
      tokenId: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    Contract(overrides?: CallOverrides): Promise<BigNumber>;

    counterOffer(
      collection: string,
      loanToken: string,
      tokenId: BigNumberish,
      principal: BigNumberish,
      interestRate: BigNumberish,
      maturity: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawBNB(
      collection: string,
      tokenId: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    Contract(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    counterOffer(
      collection: string,
      loanToken: string,
      tokenId: BigNumberish,
      principal: BigNumberish,
      interestRate: BigNumberish,
      maturity: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawBNB(
      collection: string,
      tokenId: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
